import csv
import random

categories = [
    "Future of AI and Robotics",
    "Space Exploration and Mars Colonization",
    "Environmental Sustainability and Climate Change",
    "Mental Health and Modern Psychology",
    "Philosophy and Ethics of Technology",
    "Hidden History and Lost Civilizations",
    "Evolution of Music and Art",
    "Quantum Physics and the Nature of Reality",
    "Cybersecurity and Digital Privacy",
    "Global Economics and Cryptocurrency",
    "Biotechnology and Longevity Research",
    "Urban Planning and Smart Cities",
    "Education and the Future of Learning",
    "Ocean Exploration and Marine Biology",
    "Social Media Impact on Society",
    "VR, AR, and the Metaverse",
    "Energy Crisis and Renewable Sources",
    "Modern Architecture and Design",
    "Mythology and Folk Tales",
    "Gastronomy and Food Science"
]

sub_topics = [
  "is it overrated?", "will it change everything?", "what are the ethical risks?", 
  "can it solve world hunger?", "is privacy dead?", "should it be regulated?", 
  "impact on the younger generation?", "the role of government in it?",
  "will it lead to a utopia or dystopia?", "the biggest misconception about it?",
  "how it affects our daily lives?", "historical context vs modern reality?",
  "is it a sustainable path?", "what comes next in this field?",
  "the most controversial aspect?", "unexpected benefits?", 
  "the psychological effect of it?", "best way to explain it to a child?",
  "how it will look in 50 years?", "the interface between humans and it?"
]

# Create 500 topics by mixing and matching, and adding specific ones
topics = []
for cat in categories:
    for sub in sub_topics:
        topics.append(f"{cat}: {sub}")

# Add manual specific ones to reach 500+
manual_topics = [
    "Vibe Coding: Pure trend or new standard?",
    "Why 80s synthwave is making a comeback.",
    "The mystery of the Voynich Manuscript.",
    "Can a cat understand quantum entanglement?",
    "Why some people prefer monospace fonts for everything.",
    "The paradox of choice in modern streaming services.",
    "Will remote work kill city centers?",
    "The ethics of deepfake technology in cinema.",
    "Is the 'Dead Internet Theory' becoming real?",
    "Why humans are obsessed with true crime stories.",
    "The potential of vertical farming in megacities.",
    "Could we ever build a space elevator?",
    "The psychology of procrastination.",
    "Is 'Minimalism' just a privilege for the wealthy?",
    "The future of traditional languages in a global world.",
    "Why we still find vinyl records appealing.",
    "The rise of independent game developers.",
    "What would a 100% renewable grid actually look like?",
    "The Fermi Paradox: Where is everybody?",
    "Can AI ever feel truly lonely?",
    "The impact of fast fashion on the environment.",
    "Why the smell of old books is so distinct.",
    "The transition from 2D to 3D interfaces.",
    "Is handwriting a dying art form?",
    "The role of silence in a noisy world.",
    "How coffee shaped modern civilization.",
    "The philosophy of 'Ikigai'.",
    "Will we ever have a universal basic income?",
    "The evolution of sarcasm in digital communication.",
    "The science of why we dream.",
    "Is Stoicism the best way to handle modern stress?",
    "The mystery of dark matter.",
    "How video games can teach history.",
    "The future of autonomous vehicles.",
    "Should we bring back extinct species?",
    "The importance of bees in the ecosystem.",
    "How to survive a zombie apocalypse (theoretical approach).",
    "The history of the internet's first meme.",
    "Is time travel mathematically possible?",
    "The architecture of brutalism.",
    "Why we find certain colors relaxing.",
    "The role of intuition in decision making.",
    "Could we live underground?",
    "The evolution of the superhero genre.",
    "The impact of the Printing Press vs the Internet.",
    "Why some sounds give us ASMR.",
    "The future of neural interfaces like Neuralink.",
    "Is our reality a simulation?",
    "The cultural significance of tattoos.",
    "How to build a sustainable colony on the Moon.",
    "The ethics of space tourism.",
    "Why cats 'meow' at humans but rarely at each other.",
    "The world's most remote inhabited islands.",
    "The science of habit formation.",
    "Why we love 'Old-School' aesthetic layouts.",
    "The impact of artificial light on sleep cycles.",
    "Is social media creating a 'loneliness epidemic'?",
    "The potential of solid-state batteries.",
    "How to design a city for people, not cars.",
    "The mystery of the Tunguska event.",
    "Why do we find certain patterns satisfying?",
    "The future of human-AI collaboration.",
    "Can algorithms ever be truly unbiased?",
    "The history of cryptography from Caesar to RSA.",
    "Why the 'Golden Record' was sent to space.",
    "The psychology of groupthink.",
    "How to maintain digital hygiene in a noisy world.",
    "The impact of generative art on the creative industry.",
    "Should humans settle on Mars or Venus first?",
    "The evolution of the concept of 'Privacy'.",
    "Why we are so attracted to stories with 'The Hero's Journey'.",
    "The science behind why we laugh.",
    "Is 'Work-Life Balance' a myth in 2026?",
    "The future of high-speed rail networks.",
    "How ocean currents regulate global temperature.",
    "The potential of lab-grown meat.",
    "Why chess is seeing a massive surge in popularity.",
    "The philosophy behind Open Source software.",
    "Is the world becoming too specialized?",
    "The impact of light pollution on astronomy.",
    "Why humans are drawn to 'Post-Apocalyptic' fiction.",
    "The science of memory and how to improve it.",
    "How to build a personal brand without losing your soul.",
    "The future of personalized medicine.",
    "Why we still love physical board games.",
    "The role of curiosity in scientific discovery.",
    "Is 'Boredom' necessary for creativity?",
    "The history of autonomous drones.",
    "How to design an efficient vertical city.",
    "The impact of microplastics on the food chain.",
    "Why we are fascinated by black holes.",
    "The future of 3D printing in construction.",
    "Should AI have intellectual property rights?",
    "The science of why we crave sugar.",
    "How to teach critical thinking in the age of misinformation.",
    "The role of nostalgia in consumer choice.",
    "Will physical money disappear completely?",
    "The impact of blockchain beyond finance.",
    "Why some civilizations collapsed and others thrived.",
    "The future of sustainable aviation.",
    "Can we ever reach absolute zero?",
    "The importance of 'Play' for adults.",
    "How to fix the global waste problem.",
    "The philosophy of 'Less is More'.",
    "Why humans love to explorers.",
    "The history of early computer programming.",
    "Is 'Minimalist Computing' the future?",
    "The impact of noise pollution on mental health.",
    "How to build an AI that respects human values.",
    "The future of desalination technology.",
    "Why we enjoy scary movies.",
    "The role of empathy in leadership.",
    "Is 'The Singularity' actually near?",
    "The impact of climate change on migration.",
    "Why 'Slow Living' is becoming a movement.",
    "The science of bioluminescence.",
    "How to protect the Amazon rainforest.",
    "The future of hydrogen as a fuel source.",
    "Why we find the 'Uncanny Valley' so creepy.",
    "The role of ethics in genetics.",
    "Is 'Universal Design' possible?",
    "The history of the first electronic computer.",
    "Why humans are social animals.",
    "The impact of space junk on satellite orbits.",
    "How to make internet access a basic human right.",
    "The future of energy storage.",
    "Why we find 'Retro' technology comforting.",
    "The science of emotional intelligence.",
    "How to mitigate the effects of an aging population.",
    "The philosophy of 'Transhumanism'.",
    "Why we are drawn to the unexplained.",
    "The impact of urban heat islands.",
    "How to build a culture of innovation.",
    "The future of quantum computing.",
    "Why storytelling is fundamental to human nature.",
    "The role of biodiversity in food security.",
    "Is 'Artificial General Intelligence' (AGI) achievable?",
    "The history of the scientific method.",
    "Why we value 'Authenticity'.",
    "The impact of overtourism on cultural sites.",
    "How to design a fair taxation system for the digital age.",
    "The future of work in the era of automation.",
    "Why humans seek meaning in life.",
    "The science of climate modeling.",
    "How to promote international cooperation in space.",
    "The role of ethics in planetary protection.",
    "Is 'Self-Driving' tech ready for prime time?",
    "The history of the search for extraterrestrial intelligence.",
    "Why we are captivated by the stars.",
    "The impact of antibiotic resistance.",
    "How to foster digital literacy in schools.",
    "The future of renewable energy.",
    "Why we find certain smells nostalgic.",
    "The role of philosophy in modern life.",
    "Is 'Sustainable Growth' an oxymoron?",
    "The history of the first telescope.",
    "Why humans are so adaptable.",
    "The impact of the digital divide.",
    "How to ensure data privacy in the age of AI.",
    "The future of transportation.",
    "Why we love to travel.",
    "The science of why we feel pain.",
    "How to build a more resilient society.",
    "The role of art in social change.",
    "Is 'Virtual Reality' the future of tourism?",
    "The history of the industrial revolution.",
    "Why humans are so creative.",
    "The impact of globalization.",
    "How to address the global water crisis.",
    "The future of education.",
    "Why we are drawn to stories of hope.",
    "The science of sleep deprivation.",
    "How to promote sustainable agriculture.",
    "The role of ethics in artificial intelligence.",
    "Is 'Space Colonization' necessary for human survival?",
    "The history of the first map of the world.",
    "Why humans are such complex beings.",
    "The impact of technology on human connection.",
    "How to build a more equitable world.",
    "The sense of community in the digital age.",
    "The future of healthcare.",
    "Why we find 'Simplicity' so elegant.",
    "The science of why we get bored.",
    "How to mitigate the impact of natural disasters.",
    "The role of ethics in biotechnology.",
    "Is 'The Cloud' actually good for the planet?",
    "The history of communication technology.",
    "Why humans are constantly seeking to learn.",
    "The impact of ocean acidification.",
    "How to create a more inclusive world.",
    "The future of urban living.",
    "Why we are fascinated by the concept of 'Time'.",
    "The science of why we feel happy.",
    "How to promote mental well-being in the digital age.",
    "The role of ethics in global governance.",
    "Is 'Blockchain' the key to a more transparent world?",
    "The history of the search for new worlds.",
    "Why we find 'Innovation' so exciting.",
    "The impact of air pollution on health.",
    "How to ensure access to clean energy for all.",
    "The future of food.",
    "Why we are so interested in our ancestors.",
    "The science of human behavior.",
    "How to create sustainable and livable cities.",
    "The role of ethics in environmental protection.",
    "Is 'AI' a threat or an opportunity for humanity?",
    "The history of the scientific revolution.",
    "Why humans are so diverse.",
    "The impact of the internet on culture.",
    "How to build a more peaceful world.",
    "The power of collective action.",
    "The future of humanity in space.",
    "Why we find 'Discovery' so rewarding.",
    "The science of cognitive bias.",
    "How to promote ethical data practices.",
    "The role of philosophy in understanding the universe.",
    "Is 'Technology' making us more or less human?",
    "The history of human exploration.",
    "Why we seek to understand ourselves.",
    "The impact of deforestation on climate.",
    "How to ensure energy security for the future.",
    "The future of commerce.",
    "Why we are drawn to the concept of 'Progress'.",
    "The science behind human resilience.",
    "How to build strong social foundations.",
    "The role of art in human development.",
    "Is 'Global Cooperation' the only way forward?",
    "The history of scientific breakthroughs.",
    "Why humans are so social.",
    "The impact of population growth.",
    "How to foster creativity in a world dominated by data.",
    "The ethics of decision-making in autonomous systems.",
    "The future of communication.",
    "Why we are inspired by the beauty of nature.",
    "The science of why we love music.",
    "How to build a sustainable future for the next generation.",
]

all_topics = topics + manual_topics
# Truncate or ensure unique to get around 500
final_list = list(set(all_topics))[:500]

with open('topics.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(["topic"])
    for t in final_list:
        writer.writerow([t])

print(f"Generated {len(final_list)} topics in topics.csv")
